name: Lua Language Server Analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: {submodules: recursive}

      - name: Download and extract Lua Language Server
        run: |
          mkdir -p ~/lua-ls
          curl -L https://github.com/LuaLS/lua-language-server/releases/download/3.15.0/lua-language-server-3.15.0-linux-x64.tar.gz | tar xz -C ~/lua-ls
          chmod +x ~/lua-ls/bin/lua-language-server

      - name: Run Lua Language Server
        run: ~/lua-ls/bin/lua-language-server --check . --check_out_path check.json

      - name: Process errors and create annotations
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const {readFileSync} = require('fs');
            const checkData = JSON.parse(readFileSync('check.json', 'utf8'));

            for (const [filePath, errors] of Object.entries(checkData)) {
              for (const {range, ...error} of errors) {
                const errorLevel = ({1: "error", 2: "warning"})[error.severity] || 'notice'
                core[errorLevel](
                  `${error.message}\n(error.code)`,
                  {
                    file: filePath.replace(`file://${process.cwd()}/`, ''),
                    startLine: range.start.line + 1,
                    endLine: range.end.line + 1,
                    startColumn: range.start.character + 1,
                    endColumn: range.end.character + 1,
                  }
                );
              }
            }
